name: LogBlock
version: 0.9d
author: DiddiZ, bootswithdefer
website: http://www.diddiz.de/minecraft/
main: de.diddiz.LogBlock.LogBlock
description: Logs blocks.
commands:
  lb:
    description: 'LogBlock commands.'
    usage: 'Usage: /<command> help'
    aliases: []
  lt:
    description: Alias for /lb assigntool
    usage: /<command>
  ltb:
    description: Alias for /lb assignblock
    usage: /<command>